### ISSUE TITLE
Use 'native' k8s service discovery mechanisms instead of metadata labels

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-kubernetes#17]
The implementation to discover well known middleware services such as rabbit, redis, kafka should be based on the facilities provided in Kubernetes itself as described in https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#discovering-services

Labels should not be required to exist on services.  The environment variable approach looks like a good approach.  Investigate how more complex redis setups, for example using sentinal or redis cluster configuration can be done using the environment variable approach.  See #12

**Comment by ericbottard** [comment]
Good idea, but how do you know that a given service is __e.g.__ a redis service? There will still be a need for some name convention, I believe

**Comment by markpollack** [comment]
Look at the link above for the naming conventions

**Comment by ericbottard** [comment]
I did look at the link. This tells you how the name of your service ends up in the ENV VAR, but doesn't tell you that `redis-master` (from the doc above, for example) is actually a **redis** service. I hope that makes sense.

**Comment by markpollack** [comment]
Gotya. Well there needs to be some mapping between the prefix of the env-var and the logical 'redis' or 'rabbitmq' name that we use to indicate we want to make a connection to those services.  By default we could use REDIS but pass in an override such as SERVICE_PREFIX_REDIS=REDIS_MASTER.  I'd like to work out a full example with sentinel and redis cluster.  

I'm looking around for some other best practices docs in this regard for kubernetes.  Perhaps this is a good use for confit server and/or eureka?

**Comment by ericbottard** [comment]
Thinking about it, I really think 1) using the REST API and 2) reading ENV VARS are two ways of achieving the same thing, which are orthogonal to deciding which services are redis, rabbit, etc that the user wants bound, which can be achieved by A) using labels and maybe B) C) etc..

**Comment by sabbyanandan** [comment]
Related to: #11 and #12

**Comment by sabbyanandan** [comment]
This depends on spring-cloud/spring-cloud-dataflow-admin-kubernetes#37

**Comment by jstrachan** [comment]
Service discovery in kubernetes is usually just done via a service name and a port (rather than querying kubernetes REST API using label filters etc). Usually its up to a microservice to make up its own unique service name that it wants to use. If you are worried you might look up a `redis` service when you wanted `rabbit` or whatever - just use a more explicit and descriptive name. The ports should also give you more of a clue what the service is too for non-REST stuff (e.g. redis versus rabbit)

e.g. if your inventory service wants to talk to redis; name the service `inventory-redis`. There can be many redis services in a namespace which may point to separate redis implementations (e.g. via pod selectors) or can be configured to point to the same underlying implementation (via [service endpoints](http://kubernetes.io/docs/user-guide/services/#services-without-selectors))

So for a given service name, using the DNS name to look up the service IP is usually enough. If you want you could use env vars though.

Where some discovery might help is in automatically registering secrets for a spring cloud connector; e.g. finding the user/pwd from a secret for a JDBC connection. Its a little verbose exposing secrets individually as environment variables in your pod; then referring to those environment variables in your application.properties to configure the user/pwd; discovering the secrets for services and doing the bean configuration via a library might make things a little easier to use
