### ISSUE TITLE
Elastic expansion

### ISSUE THREAD

**Issue by xyjwsj** [spring-cloud/spring-cloud-dataflow-server-kubernetes#327]
How to config dataflow-server-kubernetes elastic expansion，When a certain load is reached, automatic capacity expansion is achieved.
How to config it?

**Comment by sabbyanandan** [comment]
Hi, @xyjwsj. It is unclear what you're attempting to ask. 

For HA at SCDF server level, you can scale the server to a few instances, and by having a load-balance in front, you'd be able to round-robin the traffic. Here's [more explanation](https://stackoverflow.com/questions/43438211/loadbalancing-spring-cloud-data-flow-server) on this subject.

Whether the scaling is done manually or via an auto-scaler, it is really up to the tooling that is available in the Kubernetes itself. We do not provide anything out-of-the-box - it is a platform level responsibility.

Since it doesn't directly relate to SCDF, I'm going to close the issue.
