### ISSUE TITLE
RBAC preventing Kubernetes task launcher to access API

### ISSUE THREAD

**Issue by guillaumesmo** [spring-cloud/spring-cloud-dataflow-server-kubernetes#339]
Hello,

I'm using the Kubernetes version of SCDF 1.7.0.M1 with the `docker:springcloudstream/task-launcher-kubernetes-sink-kafka-10:1.0.0.M1` sink 

There is an issue when a TaskLaunchRequest enters the sink. 

> 2018-10-05 09:25:15.898 ERROR 1 --- [           -L-2] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/pods/task-1a12cb9c-f412-491b-88d6-626202169843-e08y6qk3ww. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "task-1a12cb9c-f412-491b-88d6-626202169843-e08y6qk3ww" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default"., failedMessage=GenericMessage [payload=TaskLaunchRequest{uri='docker:XXXXXXXX', commandlineArguments=[XXXXXXX], environmentProperties={spring_datasource_username=postgres, spring_datasource_password=postgres, spring_datasource_url=XXXXXXXXX}, deploymentProperties={}}, headers={kafka_offset=3, id=b2ed3f07-15f5-702b-f1d1-842ea98a6bee, kafka_receivedPartitionId=0, contentType=text/plain, kafka_receivedTopic=XXXXXXXXX, timestamp=1538731515880}]

I'm wondering why it's trying to use the default serviceaccount, while I have created scdf-sa. 

Also, it always tries to access the default namespace, even if you install SCDF in a custom namespace. (I have tried default, the same problem occurs)

Thanks for your help

**Comment by guillaumesmo** [comment]
The solution provided here works: https://github.com/fabric8io/fabric8/issues/6840

But I don't think granting admin roles to the default user is a viable solution :)

**Comment by sabbyanandan** [comment]
Hi, @guillaumesmo. Thank you for the report. I'd assume you're following the [getting-started guide](http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.7.0.M1/reference/htmlsingle/#kubernetes-getting-started), but if you've any customizations or more YAML steps, it'd be good to know. If possible, please also share the steps.

We will have a look on our side, too.

**Comment by guillaumesmo** [comment]
Hello, the steps are from that guide indeed, I just checked out the 1.7.0.M1 tag, didn't apply any changes to the YAML files and run the following:

    kubectl create -f src/kubernetes/kafka/
    kubectl create -f src/kubernetes/mysql/
    kubectl create -f src/kubernetes/redis/
    kubectl create -f src/kubernetes/metrics/metrics-deployment-kafka.yaml
    kubectl create -f src/kubernetes/metrics/metrics-svc.yaml
    kubectl create -f src/kubernetes/server/server-roles.yaml
    kubectl create -f src/kubernetes/server/server-rolebinding.yaml
    kubectl create -f src/kubernetes/server/service-account.yaml
    kubectl create -f src/kubernetes/server/server-config-kafka.yaml
    kubectl create -f src/kubernetes/server/server-svc.yaml
    kubectl create -f src/kubernetes/server/server-deployment.yaml

**Comment by chrisjs** [comment]
Issue 1 - Deployed application / task service account:
---
* The `scdf-sa` service account is used by the dataflow server and referenced in `src/kubernetes/server/server-deployment.yaml` under the `serviceAccountName` attribute.

* Deployed applications out of the box use service account `default`. This can be changed on a per-application basis or for all deployments in the server configuration file. The documentation for this is at: http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.7.0.BUILD-SNAPSHOT/reference/htmlsingle/#_deployment_service_account

You can use the appropriate service account for your needs. If you would like to use say `scdf-sa` here are a couple examples:

To set the deployment service account name on a task, you can do:

```
task create --definition "timestamp --format=\"yyyy\"" --name printTimeStamp
task launch --name printTimeStamp --properties "deployer.timestamp.kubernetes.deploymentServiceAccountName=scdf-sa"
```

To globally set the service account for all deployments / tasks in `src/kubernetes/server/server-deployment.yaml` you can add the following into the env section:

```
- name: SPRING_CLOUD_DEPLOYER_KUBERNETES_DEPLOYMENT_SERVICE_ACCOUNT_NAME
  value: scdf-sa
```

Issue 2 - Changing the namespace:
---
I did not find any issues with deploying DF to another namespace and have deployments/tasks reside in the custom namespace (rather than `default`). For example, I did the following in minikube:

* kubectl create namespace test

* modify `src/kubernetes/server/server-roles.yaml` and change:

```
namespace: default
```

To:

```
namespace: test
```

* modify `src/kubernetes/server/service-account.yaml` with the same change: `namespace: test`

* kubectl config set-context minikube --namespace test

* apply the stock dataflow config scripts:

```
kubectl create -f src/kubernetes/kafka/
kubectl create -f src/kubernetes/mysql/
kubectl create -f src/kubernetes/redis/
kubectl create -f src/kubernetes/metrics/metrics-deployment-kafka.yaml
kubectl create -f src/kubernetes/metrics/metrics-svc.yaml
kubectl create -f src/kubernetes/server/server-roles.yaml
kubectl create -f src/kubernetes/server/server-rolebinding.yaml
kubectl create -f src/kubernetes/server/service-account.yaml
kubectl create -f src/kubernetes/server/server-config-kafka.yaml
kubectl create -f src/kubernetes/server/server-svc.yaml
kubectl create -f src/kubernetes/server/server-deployment.yaml
```

* get the IP to use when connecting in the shell: `minikube service --url scdf-server --namespace test`

* in the shell, import task apps: `app import --uri http://bit.ly/Clark-GA-task-applications-docker`

* create a task. im also changing the deployment service account name here (using per task property format) for a full end to end test

```
task create --definition "timestamp --format=\"yyyy\"" --name printTimeStamp
task launch --name printTimeStamp --properties "deployer.timestamp.kubernetes.deploymentServiceAccountName=scdf-sa"
```

* view the configuration of the task:

```
kubectl get pod/printtimestamp-173m4meopj -o yaml
```

which shows the following correct namespace and service account:

```
  namespace: test
  ...
  selfLink: /api/v1/namespaces/test/pods/printtimestamp-173m4meopj
  ...
  ...
  serviceAccount: scdf-sa
  serviceAccountName: scdf-sa
```

and as a final sanity check to show this task landed in namespace `test` rather than `default`:

```
$ kubectl get pod printtimestamp-173m4meopj --namespace test
NAME                        READY     STATUS      RESTARTS   AGE
printtimestamp-173m4meopj   0/1       Completed   0          2m

$ kubectl get pod printtimestamp-173m4meopj --namespace default
Error from server (NotFound): pods "printtimestamp-173m4meopj" not found
```

Hopefully this helps -- all looks fine to me. Can you give it a try and update the issue with your findings? I am using all stock configs with the exceptions of the modifications made above for namespace.

**Comment by chrisjs** [comment]
Hello,

yes i think the namespace configuration can be made more flexible. ive created: https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/340 to track

**Comment by chrisjs** [comment]
closing, please re-open if you encounter any issues.
