### ISSUE TITLE
Clarify minikube resource requirement

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#344]

**Comment by chrisjs** [comment]
given it depends on what services are being deployed how many applications the user is deploying, I'm not sure how much more we can clarify this beyond what we have: 

`When starting Minikube, you should allocate some extra resources, since we deploy several services. We start with minikube start --cpus=4 --memory=4096.`

if you blow out your resources, things won't deploy and you need to add more. as mentioned, i have easily went out resources by deploying a few things then doing upgrades, roll backs, etc via Skipper which isn't Skippers fault, its just deploying/destroying applications. i personally run 8gb for the occasional times i need to deploy a bunch of stuff, but typically using much less than that.

**Comment by chrisjs** [comment]
updated based on discussion
