### ISSUE TITLE
Logging Kubernetes client error messages

### ISSUE THREAD

**Issue by mhsu0020** [spring-cloud/spring-cloud-dataflow-server-kubernetes#81]
I'm trying to deploy a stream through the data flow server and the following exception is logged:

`WARN 16835 --- [http-nio-9393-exec-2] o.s.c.d.s.c.StreamDeploymentController   : Exception when deploying the app [ModuleDefinition@41f7c559 name = 'log', label = 'log', group = 'timelog', parameters = map['spring.cloud.stream.bindings.input.destination' -> 'timelog.time', 'spring.cloud.stream.bindings.input.group' -> 'timelog']]: An error has occurred.
`

The `An error has occurred` is generated by the Fabric8 client but I can't see the tacktrace.

**Comment by sabbyanandan** [comment]
Hi, @mhsu0020: 

Thanks for trying out! 

Could you please share, how you're running the scdf-k8s-server and on what infrastructure? It'd be also helpful to know which version of scdf-k8s-server are you trying this on.

**Comment by trisberg** [comment]
I think the problem is that the Kubernetes deployer doesn't log any errors and the calling core Data Flow server code only logs the message from the exception. We should add a catch clause in the Kubernetes deployer and log more detailed exception message including the cause and stacktrace. Created issue in the Kubernetes deployer project - https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/24
